# This file describes the GitHub Actions workflow for continuous integration of CoupledL2

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master, chi-coupledl2 ]
  pull_request:
    branches: [ master, chi-coupledl2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tl-test_L2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Clang 17
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          sudo ./llvm.sh 17

      - name: Setup Scala
        uses: olafurpg/setup-scala@v10

      - name: Cache
        id: cache
        uses: coursier/cache-action@v5

      - name: Verilator
        run: |
          wget https://raw.githubusercontent.com/OpenXiangShan/xs-env/master/install-verilator.sh
          chmod u+x install-verilator.sh
          sed -i 's/CC=clang/CC=clang-17/g' install-verilator.sh
          sed -i 's/CXX=clang++/CXX=clang++-17/g' install-verilator.sh
          sed -i 's/LINK=clang++/LINK=clang++-17/g' install-verilator.sh
          sed -i 's/make -j8/make -j4/g' install-verilator.sh
          bash install-verilator.sh

      - name: Setup Mill
        uses: jodersky/setup-mill@v0.2.3
        with:
          mill-version: 0.11.1

      # - name: Check scalafmt
      #   run: make checkformat
        
      - name: Compile
        run: make compile
      
      - name: Unit test for TileLink version
        run: |
            git clone https://github.com/OpenXiangShan/tl-test-new
            cd ./tl-test-new
            rm -rf ./dut/CoupledL2 && ln -s ../.. ./dut/CoupledL2
            make coupledL2-test-l2l3l2 run THREADS_BUILD=4 CXX_COMPILER=clang++-17

      - name: Compile CHI QuadCore
        run: |
            make test-top-chi-quadcore-2ul
